### ISSUE TITLE
Subtitle incorrect.

### ISSUE THREAD

**Issue by humberto-ortiz** [rafalab/pr-covid#1]
https://github.com/rafalab/pr-covid/blob/b3e4ffa4b01b15e0ab4d9be8430d3fa9e48cd1be/dashboard/server.R#L43

The subtitle in the hospitalizations plot is incorrect. Maybe delete?

**Comment by rafalab** [comment]
That's not a subtitle. That is an annotation for the line at 695, which is the total number of ICU beds in PR. Suggestions on how to better do ti welcomed.

**Comment by humberto-ortiz** [comment]
But you're not plotting ICU cases, are you?

**Comment by rafalab** [comment]
Good point. I changed it to show hospital beds. And added a tab to the dashboard with ICU cases.
